# Generated by Django 3.0.6 on 2020-06-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dj_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='App Name')),
                ('label', models.CharField(max_length=50, verbose_name='App Label')),
                ('verbose_name', models.CharField(max_length=50, verbose_name='Verbose Name')),
            ],
            options={
                'verbose_name': 'Dj_App',
                'verbose_name_plural': 'Dj_Apps',
            },
        ),
    ]
