# Generated by Django 3.0.6 on 2020-06-03 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dj_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('verbose_name', models.CharField(max_length=100, verbose_name='Verbose Name')),
                ('verbose_name_plural', models.CharField(max_length=100, verbose_name='Verbose Plural name')),
            ],
            options={
                'verbose_name': 'Dj_Model',
                'verbose_name_plural': 'Dj_Models',
            },
        ),
        migrations.CreateModel(
            name='Dj_ModelField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Field Type')),
            ],
            options={
                'verbose_name': 'Dj_ModelField',
                'verbose_name_plural': 'Dj_ModelFields',
            },
        ),
        migrations.CreateModel(
            name='Dj_ModelLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_models.Dj_ModelField')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_models.Dj_Model')),
            ],
            options={
                'verbose_name': 'Dj_FieldModelMapping',
                'verbose_name_plural': 'Dj_FieldModelMappings',
            },
        ),
    ]
