# Generated by Django 3.0.6 on 2020-06-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj_modelline',
            name='blank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dj_modelline',
            name='null',
            field=models.BooleanField(default=False),
        ),
    ]
